# Setup
title:               Seunghyun SEO
tagline:             '서승현'
description:         '연구하고 공부한 내용을 기록'
url:                 https://seunghyunseo.github.io/
baseurl:             ''
encoding: utf-8

# Site configurations
gems:
  - jekyll-paginate
markdown: kramdown
kramdown:
  input: GFM
excerpt_separator: "<!-- more -->"
sass:
  style: compressed
  sass_dir: _scss    
paginate: 5
permalink: pretty

# About/contact
author:
  name:              Seunghyun SEO
  url:               
  email:             seosh7039@naver.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: 'UA-93172815-1'
