# Setup
title:               Seunghyun SEO
tagline:             '서승현'
description:         '정리'
url:                 https://seunghyunseo.github.io
encoding: utf-8

# Site configurations
gems:
  - jekyll-paginate
markdown: kramdown
kramdown:
  input: GFM
excerpt_separator: "<!-- more -->"
sass:
  style: compressed
  sass_dir: _scss    
paginate: 5
permalink: pretty

# About/contact
author:
  name:              Seunghyun SEO
  url:               https://seunghyunseo.github.io
  email:             seosh7039@naver.com
  
# Navigation (2nd level links supported)
nav:
  Home:           
    - '/'
  Contents:           
#     - '/blog/'
    - { Categories: '/blog/categories/' }
#     - { Tags: '/blog/tags/' }
  About:          
    - '/about/'

# Where are tags and categories displayed
# tag_page: '/blog/tags/'
category_page: '/blog/categories/'

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
mathjax: true 
google_analytics_id: 'G-Z2543B57BD'
disqus_short_name: 'https-seunghyunseo-github-io-2' 
